stages:
  train_ann:
    cmd: python models/ann_model.py
    deps:
      - models/ann_model.py
      - data/final_data/20251115_dataset_crp.csv
    outs:
      - models/model_ann.keras

  train_gru:
    cmd: python models/gru_model.py
    deps:
      - models/gru_model.py
      - data/final_data/20251115_dataset_crp.csv
    outs:
      - models/model_gru.keras

  train_lstm:
    cmd: python models/lstm_model.py
    deps:
      - models/lstm_model.py
      - data/final_data/20251115_dataset_crp.csv
    outs:
      - models/model_lstm.keras

  train_transformer:
    cmd: python models/transformer_model.py
    deps:
      - models/transformer_model.py
      - data/final_data/20251115_dataset_crp.csv
    outs:
      - models/model_transformer.keras

  train_ensemble:
    cmd: python models/ensemble_model.py
    deps:
      - data/final_data/20251115_dataset_crp.csv
      - models/ensemble_model.py
      - models/model_ann.keras
      - models/model_gru.keras
      - models/model_lstm.keras
      - models/model_transformer.keras
    outs:
      - artifacts/ensemble
      - figures