name: DVC Training & Evaluation Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[gs] tensorflow==2.15.0 mlflow scikit-learn pandas numpy matplotlib seaborn

      - name: Configure GCP credentials
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-creds.json
          gcloud auth activate-service-account --key-file=gcp-creds.json || true
          dvc remote modify gcsremote credentialpath gcp-creds.json || true

      - name: Pull dataset and models from GCS
        run: dvc pull -r gcsremote --force -v

      - name: Run DVC pipeline (including evaluation)
        run: dvc repro evaluate_models -v

      - name: Push updated artifacts and metrics to GCS
        run: |
          dvc commit evaluate_models
          dvc push -r gcsremote

      - name: Upload evaluation report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-evaluation-report
          path: reports/metrics.json